[project]
name = "mcp-wrap"
version = "0.1.0"
description = "MCP server for exposing command-line tools to LLMs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
]
